---
#
#  setup_jovyan.yml
#
new_user: 'jovyan'
new_group: 'jovyan'
new_user_uid: '1002'
new_user_gid: '1004'
#
#  setup_docker.yml
#
docker_compose_version: "1.29.2"
#
# setup_conda.yml
#
conda_prefix: /opt/miniconda3

