---
- hosts: all
  #
  # vars/jovyan_vars.yml:
  #  - git_remote_repos
  #  - git_remote_path
  #
  # vars/e211_jupyterhub.yml
  #  - e211_jupyterhub_template_list
  #
  #
  vars_files:
    - vars/jovyan_vars.yml
    - vars/git_vars.yml
    - vars/traefik_vars.yml

  tasks:
    #
    # e211 jupyterhub
    #
    # copy files to ~/repos/ubc-jupyter/jupyterhub/e211hub-image
    #
    - include_vars: "vars/jupyterhub_{{ course_name }}.yml"
    - name: fill and copy templates for jupyerhub
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        "{{ jupyterhub_template_list }}"
    - name: decrypt and copy user_list.txt
      copy:
        src: 'files/jupyterhub/{{ vault_user_list }}'
        dest: '{{ git_remote_path }}/jupyterhub/{{ hub_image_name }}-image/user_list.txt'
        decrypt: yes
        backup: no
# ansible-playbook -i hosts.yml -u jovyan -l dash -e "course_name=e211" setup_containers.yml 
