---
- hosts: all
  vars_files:
    - vars/jovyan_vars.yml
    - vars/traefik_vars.yml
    - vars/e211_jupyterhub_vars.yml
    - vars/e350_website_vars.yml
    - vars/e211_website_vars.yml
    - vars/e350_jupyterhub_vars.yml
  tasks:
    #
    # e211 jupyterhub
    #
    - name: fill and copy templates for e211hub
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        "{{ e211_jupyterhub_template_list }}"
    #https://ahelpme.com/software/ansible/ansible-using-ansible-vault-with-copy-module-to-decrypt-on-the-fly-files/
    - name: decrypt and copy e211_user_list.txt
      copy:
        src: 'files/jupyterhub/e211_vault_user_list.txt'
        dest: '{{ git_remote_path }}/jupyterhub/{{ hub_service_name }}_image/user_list.txt'
        decrypt: yes
        backup: no
    #
    #  e211 website
    #
    - name: fill and copy templates for e211 website
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop:
        "{{ e211_website_template_list }}"
    - name: make the html source folder
      file:
        path: "{{ dest_dir }}"
        state: directory
    - name: rsync the rendered book
      ansible.posix.synchronize:
        src: "{{ book_local_html }}"
        dest: "{{ dest_dir }}"
        group: "no"
        



