---
- hosts: all
  vars_files:
    - vars/jovyan_vars.yml
    - vars/git_vars.yml

  tasks:
    - name: add global gitconfig user.email
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git_email }}"

    - name: add global git user.name
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_username }}"

    - name: write credentials to .bashrc 
      blockinfile:
        marker: "# ANSIBLE GITCREDS_BLOCK"
        create: false
        dest: "~/.bashrc"
        block: "{{ gitcreds }}"

    - name: Create repositor directory
      file:
        path: "{{ git_remote_repos }}"
        state: directory

    - name: checkout git repos
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.remote_path }}"
      loop:
        "{{ git_repos_list }}"
