name: e211_notebook
channels:
  - conda-forge
dependencies:
  - mamba
  - notebook
  - jupyterhub
  - jupyterlab
  - bokeh
  - conda-lock
  - ghp-import
  - git
  - jupytext
  - matplotlib
  - numpy
  - nbgitpuller
  - pandas
  - pip
  - pillow
  - discretize
# conda-lock --kind explicit --file environment.yml -p linux-64
