name: e211_notebook
channels:
  - conda-forge
dependencies:
  - mamba
  - notebook
  - jupyterhub
  - jupyterlab
  - bokeh
  - conda-lock
  - ghp-import
  - git
  - jupytext
  - matplotlib
  - numpy
  - nbgitpuller
  - pandas
  - pip
  - pillow
  - discretize
  - empymod>=2.0.0
  - ipywidgets>=0.6.0
  - mkl>=2021.3.0
  - pymatsolver
  - scipy>=1.7
  - scikit-learn
  - SimPEG
# conda-lock --kind explicit --file environment.yml -p linux-64
