name: mainsite
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  - conda-lock
  - cvxopt
  - deepdish
  - discretize=0.7.0
  - empymod>=2.0.0
  - ipywidgets>=0.6.0
  - jupyter
  - jupyterhub
  - jupyterlab
  - jupytext
  - mamba
  - matplotlib<3.5
  - mkl>=2021.3.0
  - nbgitpuller
  - notebook
  - numpy>=1.21
  - Pillow
  - pip
  - pymatsolver
  - python=3.9
  - requests
  - scipy>=1.7
  - scikit-learn<1.0
  - SimPEG=0.15.0
# conda-lock --kind explicit --file environment.yml -p linux-64


